src/config/routes.rb
Rails.application.routes.draw do
  root 'films#index'

  devise_for :users

  resources :films do 
    member do
      put 'add'
    end
  end

  resources :categories
  
  resources :users, only: [:edit, :destroy, :index] do
    member do
      put 'request_film'
      put 'accept_request'
      put 'refuse_request'
      put 'follow'
      put 'unfollow'
      put 'give_admin'
      put 'retrieve_admin'
    end
  end
end

src/app/models/user.rb
class User < ApplicationRecord
  rolify

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :films
  has_many :user_actions_from, class_name: "UserAction", foreign_key: "from_user_id"
  has_many :user_actions_to, class_name: "UserAction", foreign_key: "to_user_id"

  # Will return an array of follows for the given user instance
  has_many :received_follows, foreign_key: :followee_id, class_name: "Following"
  # returns an array of follows a user gave to someone else
  has_many :given_follows, foreign_key: :follower_id, class_name: "Following"

  # Will return an array of users who follow the user instance
  has_many :followers, through: :received_follows, source: :follower
  # returns an array of other users who the user has followed
  has_many :followings, through: :given_follows, source: :followed_user

  attr_writer :login

  def login
    @login || self.name || self.email
  end

  def user_actions
    return (self.user_actions_to + self.user_actions_from).uniq
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      # when allowing distinct User records with, e.g., "username" and "UserName"...
      where(conditions).where(["name = :value OR lower(email) = lower(:value)", { :value => login }]).first
    elsif conditions.has_key?(:name) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

src/app/models/user_action.rb
class UserAction < ApplicationRecord
    include AASM

    belongs_to :to_user, class_name: 'User', :foreign_key => :to_user_id
    belongs_to :from_user, class_name: 'User', :foreign_key => :from_user_id

    aasm :column => :status do
        state :created, initial: true
        state :waiting
        state :accepted
        state :refused
    
        event :refuse do
          transitions from: :waiting, to: :refused
        end
    
        event :accept do
          transitions from: [:waiting, :created], to: :accepted
        end
    
        event :wait do
          transitions from: :created, to: :waiting
        end
    end

    def card_title(user_id)
        card_title = ""
        requested_action = false

        if self.from_user_id == self.to_user_id
            card_title += t('user.add_movie_to_library', user_name: User.find(self.to_user_id).name)
        elsif self.waiting?
            card_title += t('user.user_ask_lent_to_user',
                            from_user_name: User.find(self.from_user_id).name,
                            to_user_name: User.find(self.to_user_id).name
            )
            requested_action = true;
        elsif self.accepted?
            card_title += t('user.user_lent_to_user',
                            to_user_name: User.find(self.to_user_id).name,
                            from_user_name: User.find(self.from_user_id).name
            )
        elsif self.refused?
            card_title += t('user.refused_lent_ask',
                            to_user_name: User.find(self.to_user_id).name,
                            from_user_name: User.find(self.from_user_id).name
            )
        end

        status = self.waiting? ? "warning" : ( self.accepted? ? "success" : ( self.refused? ? "danger" : "primary" ) )

        return {title: card_title, status: status, requested_action: requested_action}
    end

    def status_to_text
        return "Créé" if self.created?
        return "En attente" if self.waiting?
        return "Accepté" if self.accepted?
        return "Refusé" if self.refused?
    end
    
end
  

src/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

src/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

src/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

src/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

src/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

src/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

src/app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, except: [:index, :new, :create]
    before_action :authenticate_user!, only: [:show, :edit, :update, :destroy, :respond_request]

    # GET /users
    def index
      @users = User.all
    end

    # GET /users/1
    def show
    end

    def new
    end

    def create
    end

    # GET /users/1/edit
    def edit
        @actions = @user.user_actions.sort_by {|ua| ua.id}.reverse!
    end


    # PATCH/PUT /users/1
    def update
    end

    # DELETE /posts/1
    def destroy
      @user.destroy
      redirect_to users_url, notice: "L'utilisateur a été supprimé."
    end

    def request_film

      current_user_action = UserAction.where(:film_id => params[:film_id],
                                             :to_user_id => params[:to_user_id],
                                             :from_user_id => params[:from_user_id],
                                             :status => "waiting")

      if current_user_action.empty?

        user_action = UserAction.new

        user_action.from_user_id = params[:from_user_id]
        user_action.to_user_id = params[:to_user_id]
        user_action.film_id = params[:film_id]
        user_action.status = "waiting"

        user_action.save!

        respond_to do |format|
          format.html { redirect_to films_path, notice: "Tu as demandé à #{User.find(user_action.to_user_id).name} de te prêter le film : #{Film.find(user_action.film_id).titre}" }
          format.json { head :no_content }
        end

      else

        respond_to do |format|
          format.html { redirect_to films_path, alert: "Tu as déjà demandé à #{User.find(params[:to_user_id]).name} de te prêter ce film !" }
          format.json { head :no_content }
        end

      end
    end

    def accept_request
      user_action = UserAction.find(params[:user_action_id])

      film = Film.find(user_action.film_id)
      film.user_id = user_action.from_user_id
      film.save!

      user_action.accept!

      others_user_action = UserAction.where(:film_id => user_action.film_id, :to_user_id => user_action.to_user_id, :status => "waiting")
      others_user_action.each { |ua| ua.refuse! }

      respond_to do |format|
        format.html { redirect_to edit_user_path, notice: "Tu as prêté #{film.titre} à #{User.find(user_action.from_user_id).name}" }
        format.json { head :no_content }
      end
    end

    def refuse_request
      user_action = UserAction.find(params[:user_action_id])
      user_action.refuse!

      respond_to do |format|
        format.html { redirect_to edit_user_path, notice: "Tu as refusé la demande de prêt de #{User.find(user_action.from_user_id).name}" }
        format.json { head :no_content }
      end
    end

    def follow
      Following.create(
        follower_id: params[:follower_id],
        followee_id: @user.id
      ).save!

      respond_to do |format|
        format.html { redirect_to edit_user_path(@user) }
        format.json { head :no_content }
      end
    end

    def unfollow
      f = Following.where(
        :follower_id => params[:follower_id],
        :followee_id => @user.id
      ).last

      f.delete

      respond_to do |format|
        format.html { redirect_to edit_user_path(@user) }
        format.json { head :no_content }
      end
    end

    def give_admin
      @user.add_role(:admin)

      respond_to do |format|
        format.html { redirect_to edit_user_path(@user) }
        format.json { head :no_content }
      end
    end

    def retrieve_admin
      @user.remove_role(:admin)

      respond_to do |format|
        format.html { redirect_to edit_user_path(@user) }
        format.json { head :no_content }
      end
    end

    private

    def set_user
       @user = User.find(params[:id])
    end
  end

src/app/views/users/_form.html.erb
<div class="tab-pane" id="user_form">
    <h4 class="col-sm-12"><%= t('user.video_library') %></h4>

    <ul class="nav nav-tabs" id="user-tab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="films-tab" data-toggle="tab" href="#mes-films" role="tab" aria-controls="mes-films" aria-selected="true"><%= t('user.my_films') %></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="actions-tab" data-toggle="tab" href="#mes-actions" role="tab" aria-controls="mes-actions" aria-selected="false"><%= t('user.my_actions') %></a>
    </li>
    <% if current_user && current_user == @user && !@user.followings.empty? %>
        <li class="nav-item">
            <a class="nav-link" id="actions-tab" data-toggle="tab" href="#mes-abo" role="tab" aria-controls="mes-abo" aria-selected="false"><%= t('user.my_subscriptions') %></a>
        </li>
    <% end %>
    </ul>

    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="mes-films" role="tabpanel" aria-labelledby="films-tab">
            <div class="tab-pane" id="mes-films">
                <table class="admin_table table table-striped table-bordered dataTable">
                    <thead>
                        <tr>
                            <th><%= t('film.name') %></th>
                            <th><%= t('film.title') %></th>
                            <th><%= t('film.director') %></th>
                            <% if current_user != @user %>
                            <th><%= t('film.loan') %></th>
                            <% end %>
                        </tr>
                    </thead>

                    <tbody>
                        <% @user.films.each do |film| %>
                            <tr>
                            <td><%= link_to film.id, edit_film_path(film.id) %></td>
                            <td><%= film.titre %></td>
                            <td><%= film.realisateur %></td>
                            <% if current_user != @user %>
                            <td><%= link_to  t('film.borrow'), request_film_user_path(@user, :from_user_id => current_user.id, :to_user_id => @user.id, :film_id => film.id), class: "btn btn-info float-right float-top btn-follow", method: :put %></td>
                            <% end %>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="tab-pane fade" id="mes-actions" role="tabpanel" aria-labelledby="actions-tab">
            <div class="tab-pane active" id="mes-actions">
                <% @actions.each do |a| %>
                    <% card = a.card_title(@user.id) %>
                    <div class="card text-white bg-<%=card[:status]%> mb-3">
                        <div class="card-header">#<%= a.id %> <%= a.status_to_text %></div>
                        <div class="card-body">
                            <h5 class="card-title"><%= card[:title] %></h5>
                            <p class="card-text"><i><%= Film.find(a.film_id).titre %></i>, <%= Film.find(a.film_id).realisateur %></p>

                            <% if card[:requested_action] && current_user && current_user == @user && @user.id == a.to_user_id  %>
                                <p><%= link_to t('film.accept'), accept_request_user_path(@user, :user_action_id => a.id), class: "btn btn-success float-right", method: :put %></p>
                                <p><%= link_to t('film.refuse'), refuse_request_user_path(@user, :user_action_id => a.id), class: "btn btn-danger float-right", style: "margin-right: 10px", method: :put %></p>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
        <% if current_user && current_user == @user && !@user.followings.empty? %>
            <div class="tab-pane fade" id="mes-abo" role="tabpanel" aria-labelledby="actions-tab">
                <div class="tab-pane active" id="mes-abo">
                    <div class="container" >
                        <div class="row">
                            <% @user.followings.each do |f| %> 
                                <% if !f.user_actions.empty? %> 
                                    <div class="col"> 
                                        <h5 id="follower-name"><%= f.name %></h5>
                                        <% f.user_actions.each do |a| %>
                                            <% card = a.card_title(f.id) %>
                                            <div class="card text-white bg-<%=card[:status]%> mb-3">
                                                <div class="card-header">#<%= a.id %> <%= a.status_to_text %></div>
                                                <div class="card-body">
                                                    <h5 class="card-title"><%= card[:title] %></h5>
                                                    <p class="card-text"><i><%= Film.find(a.film_id).titre %></i>, <%= Film.find(a.film_id).realisateur %></p>
                                                </div>
                                            </div>
                                        <% end %>
                                    </div>
                                <% end %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

src/app/views/users/edit.html.erb
<div class='col-md-12'>
    <div class='panel.panel-default'>
        <div class='panel-heading'>
            <h5><%= @user.name %></h5>
        </div>
    </div>
    
    <% if current_user != @user %>
        <% if current_user.has_role?(:admin) %>
            <% if @user.has_role?(:admin) %>
                <%= link_to  t('user.retrieve_admin'), retrieve_admin_user_path(@user, :admin => false), class: "btn btn-outline-info float-right float-top margin-left", method: :put %>
            <% else %>
                <%= link_to  t('user.give_admin'), give_admin_user_path(@user, :admin => true), class: "btn btn-info float-right float-top margin-left", method: :put %>
            <% end %>
        <% end %>
        <% if !current_user.followings.include?(@user) %>
            <%= link_to  t('user.follow'), follow_user_path(@user, :follower_id => current_user.id), class: "btn btn-info float-right float-top btn-follow", method: :put %>
        <% elsif user_signed_in? %>
            <%= link_to  t('user.unfollow'), unfollow_user_path(@user, :follower_id => current_user.id), class: "btn btn-outline-info float-right float-top btn-follow", method: :put %>
        <% end %>
    <% end %>

    <div class='panel-body'>
        <%= render :partial => 'form' %>
    </div>
</div>

src/app/views/users/index.html.erb
<h1>Utilisateurs</h1>

<table class="admin_table table table-striped table-bordered dataTable">
    <thead>
        <tr>
            <th>#</th>
            <th><%= t('user.login') %></th>
            <% if (user_signed_in?) && (current_user.has_role?(:admin)) %>
                <th><%= t('delete') %></th>
            <% end %>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %> 
                <tr>
                    <td> <%= link_to "##{user.id}", controller: "users", action: "edit", id: user.id %> </td>
                    <td> <%= user.name %> </td>
                    <% if (user_signed_in?) && (current_user.has_role?(:admin)) %>
                        <td style="width: 30px;"> 
                        <a><%= link_to user_path(user), method: :delete, data: { confirm: t('user.confirm_delete')} do %> 
                            <span class="iconify" data-icon="feather:trash-2" ></span>
                        <% end %></a>
                        </td>
                    <% end %>
                </tr>
        <% end %>
    </tbody>
</table>