src/config/routes.rb
Rails.application.routes.draw do
  root 'films#index'

  devise_for :users

  resources :films do 
    member do
      put 'add'
    end
  end

  resources :categories
  
  resources :users, only: [:edit, :destroy, :index] do
    member do
      put 'request_film'
      put 'accept_request'
      put 'refuse_request'
      put 'follow'
      put 'unfollow'
      put 'give_admin'
      put 'retrieve_admin'
    end
  end
end

src/app/models/film.rb
class Film < ApplicationRecord
end

src/app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy, :add]
  before_action :check_admin, except: [:index, :show, :add]

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: t('film.successfully_created') }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: t('film.successfully_updated') }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: t('film.successfully_destroyed.') }
      format.json { head :no_content }
    end
  end

  def add

    film = Film.find params[:id]

    ua = UserAction.new(
      from_user_id: current_user.id,
      to_user_id: current_user.id,
      film_id: film.id
    )
    film.user_id = current_user.id
    film.save!

    ua.save!
    ua.accept!

    respond_to do |format|
      format.html { redirect_to @film, notice: t('film.added_to_collection') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def film_params
      params.require(:film).permit(:titre, :realisateur, :timestamps)
    end

    def check_admin
      if !current_user || !current_user.has_role?(:admin)
        respond_to do |format|
          format.html { redirect_to '/', alert: t('page.insufficient_rights') }
          format.json { head :no_content }
        end
      end
    end
end

src/app/helpers/films_helper.rb
module FilmsHelper
end

src/app/views/films/_form.html.erb
<%= form_with(model: film, local: true) do |form| %>
  <% if film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
        <% film.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t('film.title') %>
    <%= form.text_field :titre %>
  </div>

  <div class="field">
    <%= form.label t('film.director') %>
    <%= form.text_field :realisateur %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/films/edit.html.erb
<h1>Editing Film</h1>

<%= render 'form', film: @film %>

<%= link_to t('page.show'), @film %> |
<%= link_to t('page.back'), films_path %>

src/app/views/films/index.html.erb
<h1>Films</h1>
<% if (user_signed_in?) && (current_user.has_role?(:admin)) %>
    <%= link_to  t('film.new'), new_film_path, class: 'counter-h1 btn btn-default' %>
<% end %>


<table class="admin_table table table-striped table-bordered dataTable">
    <thead>
        <tr>
            <th>#</th>
            <th><%= t('film.title') %></th>
            <th><%= t('film.director') %></th>
            <th><%= t('film.owner') %></th>
            <th>Created at</th>
            <% if (user_signed_in?) && (current_user.has_role?(:admin)) %>
                <th><%= t('delete') %></th>
            <% end %>
        </tr>
    </thead>
    <tbody>
        <% @films.each do |film| %> 
                <tr>
                    <td> <%= link_to "##{film.id}", controller: "films", action: "show", id: film.id %> </td>
                    <td> <%= film.titre %> </td>
                    <td> <%= film.realisateur %> </td>
                    <td> 
                    <%= link_to t('film.add') , add_film_path(film, :user_id => current_user.id), method: :put, class: 'counter-h1 btn btn-default' if film.user_id.nil? && user_signed_in? %>
                    <%= link_to User.find(film.user_id).name, edit_user_path(film.user_id) if !film.user_id.nil? %> 
                    </td>
                    <td> <%= film.created_at %> </td>
                    <% if (user_signed_in?) && (current_user.has_role?(:admin)) %>
                        <td> 
                        <a><%= link_to film_path(film), method: :delete, data: { confirm: t('film.confirm_delete')} do %> 
                            <span class="iconify" data-icon="feather:trash-2" ></span>
                        <% end %></a>
                        </td>
                    <% end %>
                </tr>
        <% end %>
    </tbody>
    <tfoot>
        <tr>
            <th>#</th>
            <th><%= t('film.title') %></th>
            <th><%= t('film.director') %></th>
            <th><%= t('film.owner') %></th>
            <th>Created at</th>
            <% if (user_signed_in?) && (current_user.has_role?(:admin)) %>
                <th><%= t('delete') %></th>
            <% end %>
        </tr>
    </tfoot>

</table>

src/app/views/films/new.html.erb
<h1><%= t('film.new') %></h1>

<%= render 'form', film: @film %>

<%= link_to t('page.back'), films_path %>

src/app/views/films/show.html.erb
<p>
  <strong><%= t('film.title') %>:</strong>
  <%= @film.titre %>
</p>

<p>
  <strong><%= t('film.director') %>:</strong>
  <%= @film.realisateur %>
</p>
<% if (!current_user.nil?) && (current_user.has_role? "admin") %>
  <%= link_to t('page.edit'), edit_film_path(@film) %> |
<% end %>
<%= link_to t('page.back'), films_path %>